### ISSUE TITLE
How to get rid of random  generator and bind data ?

### ISSUE THREAD

**Issue by kalwar** [Legioth/AllAboutGridWebinar#1]
Hi,

I would like to populate the data and bind it so that I don't use random generation. Please let me know how can I achieve this.

**Comment by Legioth** [comment]
What did you try yourself? Where did you get stuck?

**Comment by kalwar** [comment]
Thanks for the response. Actually, I got is sorted out. 
Using the util method, I simply  called container.addBean("summerDay"). And removed the random generation.
